---
title: "Untitled"
author: "Arturo Ramírez"
date: "29 de agosto de 2016"
output: 
  html_document: 
   
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#ctrl + enter para correr

#matrices

m <- matrix(nrow=2, ncol=3)
m
dim(m)

#cambio de dim de 2x3 a 3x2
dim(m) <-c(3,2)
m
#crear mtz con datos

m <- matrix(1:6,3,2)
m
m <- matrix(1:6,3,3,T)
m
class(m)

dim(m)<-c(2,5) #error de dimensión 
x <- c(1,2,3)
y <- c("a","b","c")
z <- c(x,y)
z

m1 <- rbind (m,x)
m1

m2 <- cbind(m,x)
m2

m1 <- rbind(m1,y)
m1

#Factores

x <- factor(c("si","no","si", "si","no","si","no"))
#distingue los valores
x 

table(x) 
unclass(x)
x <- factor(c("si","no","si", "si","no","si","no"),levels=c("si","no"))

x <- factor(c("azul","azul","rojo","azul","amarillo","verde","azul"))
x
table(x)

#Valores faltantes

x <- c(1,2,NaN,10,3)
is.na(x)
is.nan(x)

#Data frames

x <- data.frame(Erick=1:4, Lori=c(T,T,F,F),Jarl=c(1+1i,1i,2+3i,3+4i))
row.names(x) <-c("Primero","Segundo","Tercero","Cuarto")
x

table(x)

  nrow(x)
ncol(x)
attributes(x)

names(x) <-c("Yarely","Karen")
x
#Names no es exclusivo de data frames

x<-1:3
names(x) #null
names(x) <- c("Hugo","Paco","Luis")
x
#En listas
x<- list(a=1:10,b=100:91,c=51:60)
x
names(x) <- c("Seq1","Seq2","Seq3")
x
#para matricerls
m <- matrix(1:4,2,2)
m
attributes(m)
dimnames(m) <- list(c("Fil1","Fil2"),c("Col1","Col2"))
m

m <- matrix(NA,5,5)
m
dimnames(m) <- list(c(1:5),c("A","B","C","D","F"))
m

#coment.char="" para cuando no hay comentarios
#lectura de datos
#setwd("~/GitHub/Programacion_Actuarial_III_OT16") para cambiar el working directory

setwd("~/GitHub/Programacion_Actuarial_III_OT16")

data <-read.csv("Datos_S&P.csv")
data <-read.table("Datos_S&P.csv",T,",",nrows = 100,skip=5)
args(read.table)
data

#01/09/2016

as.logical("nacho")

#apply (lista) maply(Matriz) sapply(simplificada)

#sapply aplica la funcion class a todo data
clases <- sapply(data,class)
data <-read.table("Datos_S&P.csv",T,",",colClasses = clases)
clases

#Para guardar info, dput y dget (uso)

y <- data.frame(a=1,b="a")
dput(y)
dput(y,file="y.R")
nueva.y <- dget("y.R")
y
nueva.y

x <- "Programación actuarial III"
y <- data.frame(a=1,b="a")
dump(c("x","y"), file="data.R") #Comillas para seleccionar el objeto, no el valor
rm(x,y) #remove
source("data.R") #mandas a llamar al objeto

dput(airquality)
dput(airquality, file="airquality.R")


url(www.google.com)
url("www.google.com")

#r read only, readLines=ver las x primeras lineas
con <- url("http://www.fcfm.buap.mx/","r")
x <- readLines(con,7)
x
#writeLines toma un vector de caracteres y escribe c/elemento en una linea a la vez en 
#un archivo de texto

# [ extrae un obj de la misma clase al original
#[[ Extrae un elemento de una lista o data frame, extrae solo un elemento
# $ se usa para extraer elementos de una lista o data frame por nombre

#Con restricción x[x>"b"] "x tales que x son > que b"

#Ejemplo
x <- c("a","b","c","c","d","e")
x
#extraemos elementos
x[1]
#extraemos una secuencia
x[1:4]
#con restricción
x[x>"b"]
#Para obtener un vector logico
u <- x == "c"
u
x[u]

#creamos una lista
x <- list(foo=1:4, bar=.6)
#extraemos el 1er elem
#es una secuencia
x[1]
#Extrae la lista entera

#extraemos el 1er elem de nuevo
x[[1]]
#extrae el ELEMENTO de la lista

x$bar
x[["bar"]]
x["bar"]
#es lo mismo

